services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    ports:
      - "5454:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: