spring:
  application:
  name: banking.demo
  datasource:
    url: ${DEMO_DB_URL}
    username: ${DEMO_DB_USR}
    password: ${DEMO_DB_PASS}
    jpa:
      hibernate:
        ddl-auto: true
      show-sql: true

  flyway:
    enabled: true
    url: ${DEMO_DB_URL}
    user: ${DEMO_DB_USR}
    password: ${DEMO_DB_PASS}
    locations: classpath:db/migration


server:
  port: 8081