spring:
  application:
  name: banking.demo


  datasource:
    url: jdbc:postgresql://db:5432/demo
    username: demo
    password: demo
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
