spring:
  application:
  name: banking.demo


  datasource:
    url: jdbc:postgresql://localhost:5454/demo
    username: demo
    password: demo
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
  flyway:
    enabled: true
    url:  jdbc:postgresql://localhost:5454/demo
    user: demo
    password: demo
    locations: classpath:db/migration


server:
  port: 8081