spring:
  application:
  name: banking.demo
  datasource:
    url: jdbc:postgresql://localhost:5543/demo?stringtype=unspecified
    username: postgres
    password: root
    jpa:
      hibernate:
        ddl-auto: true
      show-sql: true

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5543/demo?stringtype=unspecified
    user: postgres
    password: root
    locations: classpath:db/migration


server:
  port: 8081